#!/usr/bin/env python
#
# ThingDoc - things comment parser - http://thingdoc.org/
# Copyright (C) 2011 Josef Prusa <iam@josefprusa.cz>
# Copyright (C) 2011 Pavol Rusnak <stick@gk2.sk>
# See the file AUTHORS for all contributions
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION = '1.0'

import optparse
import os
import sys

class Thing:

	def __init__(self):
		self.id = None          # unique id, root has id = 0 (numeric) which cannot be overriden
		self.name = None        # name of the thing
		self.common = False     # is this thing common?
		self.assembled = False  # is this thing assembled?
		self.category = ''      # category of the thing
		self.type = ''          # type of the thing (more detailed than category, e.g. RP, fastener, etc)
		self.step = []          # assembly instructions (aka steps)
		self.since = ''         # since when does the thing exist (can be YYYY-MM-DD or some tag, e.g. "Mendel")
		self.comment = []       # comments
		self.image = None       # thing image (filename with extension)
		self.using = []         # list of dependencies (their {id}s)
		self.price = None       # price of the thing (in $) - experimental
		self.weight = None      # weight of the thing (in grams) - experimental
		self.time = None        # how long does it take to assemble the part (in minutes) - experimental
		self.desc = []          # description of the thing


def warning(string):
	print >> sys.stderr, 'Warning:', string


def error(string):
	print >> sys.stderr, 'Error:', string


def fatal(string):
	print >> sys.stderr, 'Fatal:', string
	sys.exit(1)


def process_file(absname, things):

	try:
		f = open(absname, 'r')
	except IOError:
		fatal('Cannot open file %s' % absname)

	success = True
	thing = None
	linenum = 0
	for line in f:
		linenum += 1
		if line.startswith('/**'):
			if thing:
				error('Start of the comment (/**) found but the previous one is still open (%s:%d)' % (absname, linenum))
				success = False
			thing = Thing()
			continue
		if line.startswith(' */'):
			if not thing:
				error('End of the comment ( */) found but there is no previous open one (%s:%d)' % (absname, linenum))
				success = False
				continue
			if not thing.id:
				error('Missing mandatory attribute @id (%s:%d)' % (absname, linenum))
				success = False
			if not thing.name:
				error('Missing mandatory attribute @name (%s:%d)' % (absname, linenum))
				success = False
			if thing.id and thing.name:
				if thing.id in things:
					if thing.id == 1:
						fatal('More than one @root detected!')
					else:
						error("Duplicate thing id: '%s' (%s:%d)" % (thing.id, absname, linenum))
						success = False
				else:
					things[ thing.id ] = thing
			thing = None
			continue
		if not thing:
			continue  # not in a comment
		if not line.startswith(' * '):
			error('Comment line does not start with a " * " (%s:%d)' % (absname, linenum))
			success = False
			continue
		(key, _, value) = line[3:].strip().partition(' ')
		if   key == '@id':
			thing.id = value
		elif key == '@name':
			thing.name = value
		elif key == '@root':
			thing.id = 1
		elif key == '@common':
			thing.common = True
		elif key == '@assembled':
			thing.assembled = True
		elif key == '@since':
			thing.since = value
		elif key == '@category':
			thing.category = value
		elif key == '@type':
			thing.type = value
		elif key == '@step':
			thing.step.append(value)
		elif key == '@comment':
			thing.comment.append(value)
		elif key == '@image':
			thing.image = value
		elif key == '@using':
			(cnt, _, id) = value.partition(' ')
			try:
				cnt = int(cnt)
			except:
				id = cnt
				cnt = 1
			thing.using.append( (cnt, id) )
		elif key == '@price':
			thing.price = float(value)
		elif key == '@weight':
			thing.weight = float(value)
		elif key == '@time':
			thing.weight = float(time)
		elif key.startswith('@'):
			error('Unknown tag %s (%s:%d)' % (key, absname, linenum))
			success = False
		else:
			thing.desc.append(key + ' ' + value)
	f.close()
	return success


def generate_tree(indir):

	things = {}
	for root, dirs, files in os.walk(os.path.abspath(indir)):
		dirs[:] = [d for d in dirs if not d.startswith('.')]
		for name in files:
			# skip if the file is not supported document
			if not os.path.splitext(name)[1] in ['.scad', '.tdoc']:
				continue
			absname = os.path.join(root, name)
			process_file(absname, things)
	return things


def check_tree(tree):

	if not 1 in tree:
		fatal('Nothing was declared as @root')

	# do BFS on dependency graph
	used = []
	missing = []
	queue = [1]
	while queue:
		thing = queue.pop()
		if not thing in tree.iterkeys():
			if not thing in missing:
				missing.append(thing)
			continue
		if not thing in used:
			used.append(thing)
			queue += map(lambda x: x[1], tree[thing].using)

	# handle unused things
	for thing in tree.iterkeys():
		if not thing in used:
			warning("Thing '%s' is defined but unused" % thing)

	valid = True

	# handle undefined things
	for thing in missing:
		parents = []
		for k, v in tree.iteritems():
			if thing in map(lambda x: x[1], v.using):
				parents.append(k == 1 and '@root' or ("'" + k + "'"))
		parents.sort()
		error("Thing '%s' is not defined and required by: %s" % (thing, ', '.join(parents)))
		valid = False

	# detect oriented cycles
	todo = tree.keys()
	while todo:
		node = todo.pop()
		stack = [node]
		while stack:
			top = stack[-1]
			for node in map(lambda x: x[1], tree[top].using):
				if node in stack:
					error("Oriented cycle detected: '%s'" % ("' -> '".join(stack[stack.index(node):] + [node])))
					valid = False
					todo = []
					stack = []
					break
				if node in todo:
					stack.append(node)
					todo.remove(node)
					break
			else:
				node = stack.pop()

	if not valid:
		fatal('Tree validation failed, see errors above')


def print_tree(tree):

	queue = [(0, 1, -1)]
	while queue:
		(cnt, id, level) = queue.pop(0)
		if id == 1:
			print '@root', '(' + tree[id].name + ')'
		else:
			print level * '  ', '-', str(cnt) + 'x', tree[id].id, '(' + tree[id].name + ')'
		queue = map(lambda x: (x[0], x[1], level + 1), tree[id].using) + queue


def graphviz_tree(tree, bom):

	print 'digraph thingdoc {'
	print '\tnode [style=filled, colorscheme=pastel19];'
	print '\tedge [dir=back];'
	queue = [(0, 1, ['!'])]
	while queue:
		(cnt, id, path) = queue.pop(0)
		if id == 1:
			print '\t"!"[label="%s", fillcolor=9];' % tree[id].name
		else:
			name = tree[id].name
			if cnt > 1:
				name = '%dx %s' % (cnt, name)
			if tree[id].common:
				color = 1
			elif not tree[id].category:
				color = 8
			else:
				i = bom.keys().index(tree[id].category)
				color = (i % 6) + 2 # 2-7
			print '\t"%s"[label="%s", fillcolor=%d];' % ('/'.join(path), name, color)
			print '\t"%s" -> "%s";' % ('/'.join(path[:-1]), '/'.join(path))
		queue = map(lambda x: (x[0], x[1], path + [x[1]]), tree[id].using) + queue
	print '}'


def extract_bom(tree):

	queue = [ tree[1].using  ]
	bom = {}
	while queue:
		using = queue.pop(0)
		for (cnt, id) in using:
			if tree[id].category in bom:
				bomcat = bom[tree[id].category]
				if id in bomcat:
					bomcat[id] += cnt
				else:
					bomcat[id] = cnt
			else:
				if tree[id].category:
					bom[tree[id].category] = {id: cnt}
			queue += [ tree[id].using ]
	return bom


def extract_instructions(tree, id):

	instr = []
	for (_, cid) in tree[id].using:
		instr += extract_instructions(tree, cid)
	if tree[id].step:
		instr.append( ['Assemble ' + tree[id].name] + tree[id].step )
	return instr


def generate_bom(tree, bom):

	try:
		f = open('bom.txt', 'w')
	except:
		error('Cannot create bom.txt')
		return
	f.write('Bill of Materials: %s\n' % tree[1].name)
	f.write((len(tree[1].name) + 19) * '+' + '\n\n')
	for category in bom:
		f.write(category + '\n')
		f.write(len(category) * '=' + '\n')
		for k, v in bom[category].iteritems():
			f.write('- %dx %s\n' % (v, tree[k].name))
		f.write('\n')
	f.write('----\nGenerated by ThingDoc - http://thingdoc.org/\n')
	f.close()


def cleanup_html(string):
	if isinstance(string, (list, tuple)):
		return tuple(map(lambda x: isinstance(x, str) and x.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;') or x, string))
	else:
		return string.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def generate_html(tree, bom, instr, imagedir):

	try:
		f = open('thingdoc.html', 'w')
	except:
		error('Cannot create thingdoc.html')
		return

	f.write('''<html>
  <head>
    <title>ThingDoc: %s</title>
  </head>
  <body>

    <h1>ThingDoc: %s</h1>

''' % cleanup_html((tree[1].name, tree[1].name))
	)
	if tree[1].image:
		f.write('    <img src="%s/%s" width="512" />\n' % cleanup_tex((imagedir, tree[1].image)))

	# BOM
	f.write('    <h2>Bill of Materials</h2>\n\n')
	for category in bom:
		f.write('    <h3>%s</h3>\n' % cleanup_html(category))
		f.write('    <ul>\n')
		for k, v in bom[category].iteritems():
			f.write('      <li>%dx %s</li>\n' % cleanup_html((v, tree[k].name)))
		f.write('    </ul>\n\n')

	# Things overview
	f.write('    <h2>Things overview</h2>\n')
	f.write('    <p>List of things and their descriptions</p>\n\n')
	for thing in tree.itervalues():
		if thing.id != 1 and thing.common == False:
			f.write('    <h3>%s</h3>\n' % cleanup_html(thing.name))
			if thing.desc:
				f.write('      <p>%s</p>\n' % '\n'.join(thing.desc))
			if thing.image:
				f.write('      <img src="%s/%s" width="256" />\n' % cleanup_tex((imagedir, thing.image)))
			f.write('\n')

	# Assembly instructions
	f.write('    <h2>Assembly instructions</h2>\n')
	for i in instr:
		f.write('      <h3>%s</h3>\n' % i[0])
		f.write('      <ol>\n')
		for j in i[1:]:
			f.write('        <li>%s</li>\n' % j)
		f.write('      </ol>\n')

	f.write('''    <p class="footer">Generated by ThingDoc - <a href="http://thingdoc.org/">http://thingdoc.org/</a></p>
  </body>
</html>
''')
	f.close()


def generate_wiki(tree, bom):

	try:
		f = open('thingdoc.wiki', 'w')
	except:
		error('Cannot create thingdoc.wiki')
		return

	f.write('== Bill of Materials ==\n')
	for category in bom:
		f.write('=== %s ===\n{| class="wikitable sortable" border="1"\n|-\n! scope="col" | Quantity\n! scope="col" | Description\n! scope="col" | Type\n! scope="col" class="unsortable" | Comments\n! scope="col" class="unsortable" | Diagram\n' % category)
		for k, v in bom[category].iteritems():
			img = tree[k].image and ' [[File:%s|50px]]' % tree[k].image or ''
			f.write('|-\n| %d || %s || %s || %s ||%s\n' % (v, tree[k].name, tree[k].type, '; '.join(tree[k].comment), img))
		f.write('|}\n')
	f.close()


def cleanup_tex(string):
	if isinstance(string, (list, tuple)):
		return tuple(map(lambda x: isinstance(x, str) and x.replace('&', '\\&') or x, string))
	else:
		return string.replace('&', '\\&')


def generate_tex(tree, bom, instr, imagedir):

	try:
		f = open('thingdoc.tex', 'w')
	except:
		error('Cannot create thingdoc.tex')
		return

	f.write("""\\documentclass[11pt]{article}
\\usepackage[latin2]{inputenc}
\\usepackage{a4wide}
\\usepackage{graphicx}
\\title{%s documentation}
\\author{generated by ThingDoc}
\\begin{document}
\\maketitle
%s
""" % cleanup_tex((tree[1].name, '\n'.join(tree[1].desc))))

	if tree[1].image:
		f.write('\\begin{center}\n')
		f.write('\\includegraphics[width=8cm]{%s/%s}\n' % cleanup_tex((imagedir, tree[1].image)))
		f.write('\\end{center}\n')

	f.write("""\\newpage
\\tableofcontents
\\newpage
""")

	# BOM
	f.write('\\section{Bill of materials}\n')
	f.write('List of things you need to build the machine divided by categories\n')
	for category in bom:
		f.write('\\subsection{%s}\n\\begin{itemize}\n' % cleanup_tex(category))
		for k, v in bom[category].iteritems():
			f.write('\\item %dx %s\n' % cleanup_tex((v, tree[k].name)))
		f.write('\\end{itemize}\n')
	f.write('\\newpage\n')

	# Things overview
	f.write('\\section{Things overview}\n')
	f.write('List of things and their descriptions\n')
	for thing in tree.itervalues():
		if thing.id != 1 and thing.common == False:
			f.write('\\subsection{%s}\n' % cleanup_tex(thing.name))
			if thing.desc:
				f.write('\n'.join(thing.desc) + '\n')
			if thing.image:
				f.write('\\includegraphics[width=4cm]{%s/%s}\n' % cleanup_tex((imagedir, thing.image)))
			f.write('\n')
	f.write('\\newpage\n')

	# Assembly instructions
	f.write('\\section{Assembly instructions}\n')
	for i in instr:
		f.write('\\subsection{%s}\n' % i[0])
		f.write('\\begin{itemize}\n')
		for j in i[1:]:
			f.write('\\item %s\n' % j)
		f.write('\\end{itemize}\n')
	f.write('\\newpage\n')

	f.write('\\end{document}\n')


def main():

	parser = optparse.OptionParser(
		version = '%prog ' + VERSION,
		epilog = 'If none of --bom, --html, --tex, --wiki are provided then all 4 types are generated.')
	parser.add_option('-i', '--indir', dest = 'indir', default = '.', help = 'start scanning in INDIR directory (current by default)', metavar = 'INDIR')
	parser.add_option('-o', '--outdir', dest = 'outdir', default = 'docs', help = 'use OUTDIR as output directory ("docs" by default)', metavar = 'OUTDIR')
	parser.add_option('--imagedir', dest = 'imagedir', default = 'images', help = 'use IMAGEDIR subdirectory in OUTDIR for images used in HTML and TeX ("images" by default)', metavar = 'IMAGEDIR')
	parser.add_option('-l', '--lint', dest = 'lint', default = None, help = 'check syntax in FILE and exit', metavar = 'FILE')
	parser.add_option('-b', '--bom', action = 'store_true', dest = 'bom', default = False, help = 'generate Bill of Materials')
	parser.add_option('-m', '--html', action = 'store_true', dest = 'html', default = False, help = 'generate HTML (markup) documentation')
	parser.add_option('-t', '--tex', action = 'store_true', dest = 'tex', default = False, help = 'generate TeX documentation')
	parser.add_option('-w', '--wiki', action = 'store_true', dest = 'wiki', default = False, help = 'generate Wiki documentation')
	parser.add_option('-p', '--print', action = 'store_true', dest = 'tree', default = False, help = 'print tree of things and exit (text mode)')
	parser.add_option('-g', '--graph', action = 'store_true', dest = 'graphviz', default = False, help = 'generate graphviz document')

	(options, _) = parser.parse_args()

	if options.lint:
		if process_file(options.lint, {}):
			print 'No syntax errors detected'
			sys.exit(0)
		else:
			sys.exit(1)

	if not options.bom and not options.html and not options.tex and not options.wiki:
		options.bom = options.html = options.tex = options.wiki = True

	tree = generate_tree(options.indir)

	try:
		os.makedirs(options.outdir)
	except:
		pass
	try:
		os.chdir(options.outdir)
	except:
		fatal('Cannot switch to OUTDIR: %s' % options.outdir)

	check_tree(tree)

	bom = extract_bom(tree)
	instr = extract_instructions(tree, 1)

	if options.tree:
		print_tree(tree)
		return

	if options.graphviz:
		graphviz_tree(tree, bom)
		return

	if options.bom:
		generate_bom(tree, bom)
	if options.html:
		generate_html(tree, bom, instr, options.imagedir)
	if options.tex:
		generate_tex(tree, bom, instr, options.imagedir)
	if options.wiki:
		generate_wiki(tree, bom)

	print 'All Done!'


if __name__ == '__main__':
	main()
